app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session, current_app
from flask_mail import Message
import hashlib
import random
import string
from itsdangerous import URLSafeTimedSerializer
from app.models.database import dbConnect

auth_bp = Blueprint('auth', __name__)

def generate_token(length=20):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(length))

@auth_bp.route('/logowanie', methods=["POST","GET"])
def logowanie_action():
	if 'login' in session:
		return redirect("/")
	if request.method == "POST":
		login = request.form["login"].lower()
		haslo = request.form["haslo"]
		if login=="" or haslo=="":
			msg = "Nie wszystkie pola zostały wypełnione"
		else:
			haslo = hashlib.sha256(haslo.encode('utf-8')).hexdigest()
			dbConnection = dbConnect()
			dbCursor = dbConnection.cursor()
			dbCursor.execute("SELECT id_uzytkownika, haslo, rola, weryfikacja FROM uzytkownicy WHERE login = '{}'".format(login))
			haslo2 = dbCursor.fetchall()
			if len(haslo2)==0 or haslo!=haslo2[0][1]:
				msg = "Błędne dane logowania"
				return render_template("logowanie.html", msg=msg)
			else:
				if haslo2[0][3] == False:
					msg = 'Konto nie zostało jeszcze aktywowane. Zaloguj się na pocztę i wejdz w link aktywacyjny.'
					return render_template('logowanie.html',msg=msg)
				if haslo2[0][2] == 'ban':
					msg = 'Konto zostało zbanowane.'
					return render_template('logowanie.html', msg=msg)
				session['login'] = login
				session['userid'] = haslo2[0][0]
				session['rola'] = haslo2[0][2]
				return redirect("/")
		return render_template("logowanie.html", msg=msg)	
	return render_template("logowanie.html")

#@app.route('/rejestracja')
#def rejestracja():
#	if 'login' in session:
#		return redirect("/")
#	return render_template("rejestracja.html")
	
@auth_bp.route('/rejestracja', methods=['POST','GET'])
def rejestracja():
	if 'login' in session:
		return redirect("/")
	msg=''
	if request.method == "POST":
		login = request.form["login"].lower()
		haslo = request.form["haslo"]
		haslo2 = request.form["haslo2"]
		imie = request.form["imie"]	
		nazwisko = request.form["nazwisko"]
		nr_tel = request.form["nr_tel"]
		plec = request.form["plec"]
		
		if haslo != haslo2:
			msg = "Hasła nie są takie same"
		elif login=="" or haslo=="" or haslo2=="":
			msg = "Nie wszystkie pola zostały wypełnione"
		else:
			dbConnection = dbConnect()
			dbCursor = dbConnection.cursor()

			dbCursor.execute("SELECT login FROM uzytkownicy WHERE login = '{}';".format(login))
			check = dbCursor.fetchall()
			if len(check)!=0:
				msg = "Istnieje już użytkownik o podanej nazwie"
				return render_template("rejestracja.html", msg=msg)
			else:
				
				confirmation_token = generate_token()
				
				haslo = hashlib.sha256(haslo.encode('utf-8')).hexdigest()
				dbCursor.execute('''INSERT INTO uzytkownicy VALUES (default,%s,%s,%s, %s, %s,%s, CURRENT_DATE,default,default,%s)''', (imie, nazwisko, nr_tel, login, haslo, plec,confirmation_token))
				dbConnection.commit()
				msg = Message('Potwierdzenie rejestracji', sender='letsbefit.silownia@gmail.com', recipients=[login])
				msg.body = f'Kliknij poniższy link, aby potwierdzić rejestrację: {url_for("auth.confirm", token=confirmation_token, _external=True)}'
				current_app.extensions['mail'].send(msg)
				msg = "Konto utworzone prawidłowo, aby móc się zalogować wejdź w link aktywacyjny wysłany na podanego maila"
			dbCursor.close()
			dbConnection.close()
			return render_template("index.html",msg=msg)
	
	return render_template("rejestracja.html",msg=msg)



@auth_bp.route('/confirm/<token>')
def confirm(token):
    # Znajdź użytkownika po tokenie
	dbConnection = dbConnect()
	dbCursor = dbConnection.cursor()
	dbCursor.execute("SELECT * FROM uzytkownicy WHERE token_potwierdzajacy = %s", (token,))
	user = dbCursor.fetchone()

	if user:
        # Zaktualizuj status potwierdzenia
		dbCursor.execute("UPDATE uzytkownicy SET weryfikacja = true WHERE id_uzytkownika = %s", (user[0],))
		dbConnection.commit()

		msg='Rejestracja potwierdzona. Możesz się teraz zalogować.'
	else:
		msg='Błąd potwierdzenia rejestracji. Spróbuj ponownie lub skontaktuj się z administratorem.'
	
	return redirect(url_for('admin.index',msg=msg))


@auth_bp.route('/reset_hasla', methods=['GET', 'POST'])
def reset_hasla():
	if request.method == 'POST':
		email = request.form['email']
		dbConnection = dbConnect()
		dbCursor = dbConnection.cursor()
		dbCursor.execute("SELECT * FROM uzytkownicy WHERE login = 'arekimmobile@gmail.com'")  #%s", (email,))
		user = dbCursor.fetchone()

		if user:
			serializer = URLSafeTimedSerializer(current_app.secret_key)
			token = serializer.dumps(email, salt='reset-hasla-salt')
			msg = Message('Resetowanie hasła', sender='letsbefit.silownia@gmail.com', recipients=[email])
			#reset_url = url_for('reset_hasla_potwierdzenie', token=token, _external=True)
			confirmation_url = url_for('auth.reset_hasla_potwierdzenie', token=token, _external=True)
			msg.body = f'Aby zresetować hasło, kliknij poniższy link:\n{confirmation_url}'
			current_app.extensions['mail'].send(msg)
			msgSuccess = 'Link resetujący hasło został wysłany na podany adres e-mail.'
			return render_template('reset_hasla.html',msgSuccess=msgSuccess)

	return render_template('reset_hasla.html')

# Endpoint do potwierdzenia resetowania hasła
@auth_bp.route('/reset_hasla_potwierdzenie/<token>', methods=['GET', 'POST'])
def reset_hasla_potwierdzenie(token):
	try:
		serializer = URLSafeTimedSerializer(current_app.secret_key)
		email = serializer.loads(token, salt='reset-hasla-salt', max_age=3600)
    
	except Exception as e:
		print(f"Błąd przy odczycie tokenu: {e}")
		return redirect(url_for('auth.index'))

	if request.method == 'POST':
		nowe_haslo = request.form['nowe_haslo']
		nowe_haslo2 = request.form['nowe_haslo2']

		if nowe_haslo != nowe_haslo2:
			msg = 'Hasła nie są takie same'
			return render_template('reset_hasla_potwierdzenie.html', token=token, email=email,msg=msg)
		else:
			nowe_haslo = request.form['nowe_haslo']
			nowe_haslo_hash = hashlib.sha256(nowe_haslo.encode('utf-8')).hexdigest()
			dbConnection = dbConnect()
			dbCursor = dbConnection.cursor()
			dbCursor.execute("UPDATE uzytkownicy SET haslo = %s WHERE login = %s", (nowe_haslo_hash, email))
			dbConnection.commit()
			msg= 'Hasło zostało zresetowane. Możesz się teraz zalogować.'
			return redirect(url_for('auth.logowanie_action', msg=msg))

	return render_template('reset_hasla_potwierdzenie.html', token=token,email=email)



@auth_bp.route('/wyloguj')
def wyloguj():
	if 'login' in session:
		session.clear()
	return redirect("/")

app/routes/profile.py
from flask import Blueprint, render_template, session, redirect
from flask_paginate import Pagination, get_page_args
from app.models.database import dbConnect, PER_PAGE

profile_bp = Blueprint('profile', __name__)

@profile_bp.route('/profil')
def profil():
	if 'login' not in session:
		return redirect('/')
	page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
	userid = session['userid']
	login = session['login']

	dbConnection = dbConnect()
	dbCursor = dbConnection.cursor()
	dbCursor.execute("SELECT id_uzytkownika, imie, nazwisko, nr_tel, login, plec, data_dolaczenia FROM uzytkownicy WHERE login = '{}'".format(login))
	res = dbCursor.fetchall()
	dbCursor.execute("SELECT uzytkownicy.id_uzytkownika FROM uzytkownicy, karnet WHERE uzytkownicy.id_uzytkownika=karnet.id_wlasciciela and (current_date between karnet.data_rozpoczecia_karnetu and karnet.data_zakonczenia_karnetu) and uzytkownicy.id_uzytkownika = '{}' ".format(userid))
	res2 = dbCursor.fetchall()
	if(res2):	status_karnetu="aktywny"
	else:	status_karnetu="nieaktywny"
	# Zlicz wszystkie rekordy przed zastosowaniem paginacji
	dbCursor.execute("SELECT idkarnetu, typ_karnetu, wartosc, data_zakupu, data_rozpoczecia_karnetu, data_zakonczenia_karnetu FROM karnet WHERE id_wlasciciela = %s ORDER BY data_zakupu desc,idkarnetu desc", (userid,))
	total_records = dbCursor.rowcount
	# Ograniczenie zapytania do odpowiedniej strony
	pagination = Pagination(page=page, per_page=per_page, total=total_records, css_framework='bootstrap5')
    
	dbCursor.execute("SELECT idkarnetu, typ_karnetu, wartosc, data_zakupu, data_rozpoczecia_karnetu, data_zakonczenia_karnetu FROM karnet WHERE id_wlasciciela = %s ORDER BY data_zakupu desc, idkarnetu desc LIMIT %s OFFSET %s", (userid, PER_PAGE, offset))
	res3 = dbCursor.fetchall()
	karnety_ids=[]
	if 'login' in session:
			dbCursor.execute("SELECT idkarnetu FROM karnet WHERE id_wlasciciela = %s and current_date between karnet.data_rozpoczecia_karnetu and karnet.data_zakonczenia_karnetu", (session['userid'],))
			karnety_ids = [result[0] for result in dbCursor.fetchall()]
	dbConnection.commit()
	dbCursor.close()
	dbConnection.close()

	return render_template("profil.html", pagination=pagination,karnety_ids=karnety_ids, ticket_list=res3, id=res[0][0], imie=res[0][1], nazwisko=res[0][2], nr_tel=res[0][3], login=res[0][4], plec=res[0][5], data_dolaczenia=res[0][6], status_karnetu=status_karnetu)


@profile_bp.route('/profil_trenera')
def profil_trenera():
	if 'login' not in session:
		return redirect('/')
	elif session['rola'] != 'trener':
		return redirect('/')
	page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
	userid = session['userid']
	login = session['login']

	dbConnection = dbConnect()
	dbCursor = dbConnection.cursor()
	dbCursor.execute("SELECT id_uzytkownika, imie, nazwisko, nr_tel, login, plec, data_dolaczenia FROM uzytkownicy WHERE login = '{}'".format(login))
	res = dbCursor.fetchall()
	dbCursor.execute("SELECT uzytkownicy.id_uzytkownika FROM uzytkownicy, karnet WHERE uzytkownicy.id_uzytkownika=karnet.id_wlasciciela and (current_date between karnet.data_rozpoczecia_karnetu and karnet.data_zakonczenia_karnetu) and uzytkownicy.id_uzytkownika = '{}' ".format(userid))
	res2 = dbCursor.fetchall()
	if(res2):	status_karnetu="aktywny"
	else:	status_karnetu="nieaktywny"
    # Zlicz wszystkie rekordy przed zastosowaniem paginacji
	dbCursor.execute("SELECT nazwa_zajec, opis_zajec, data_zajec, godzina_zajec, czas_zajec, id_zajec FROM zajecia WHERE id_trenera = %s and data_zajec>CURRENT_DATE  ORDER BY data_zajec asc, godzina_zajec asc", (userid,))
	total_records = dbCursor.rowcount
    # Ograniczenie zapytania do odpowiedniej strony
	pagination = Pagination(page=page, per_page=per_page, total=total_records, css_framework='bootstrap4')
    
	dbCursor.execute("SELECT nazwa_zajec, opis_zajec, data_zajec, godzina_zajec, czas_zajec, id_zajec FROM zajecia WHERE id_trenera = %s and data_zajec>CURRENT_DATE ORDER BY data_zajec asc, godzina_zajec asc  LIMIT %s OFFSET %s", (userid, PER_PAGE, offset))

	res3 = dbCursor.fetchall()

	dbConnection.commit()
	dbCursor.close()
	dbConnection.close()

	return render_template("profil_trenera.html", pagination=pagination, lista_zajec=res3, id=res[0][0], imie=res[0][1], nazwisko=res[0][2], nr_tel=res[0][3], login=res[0][4], plec=res[0][5], data_dolaczenia=res[0][6])

app/templates/karnety_recepcja.html
{%extends "base.html"%}
{%block content%}

  <div class="row justify-content-around" style="margin-top:12px">
    <div class="card cardp text-white bg-dark mb-3" style="">
        <div class="card-body">
          <h5 class="card-title text-primary mt-2">Sprzedaż karnetu</h5>
          <hr class="bg-light">
          
          {%if msgSuccess %}<p class="text-success">{{msgSuccess}}</p>{%endif%}
            <div class=" ">
              <form action="/recepcja_zapisz_karnet" method="POST"  id="zapisForm" >
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <p>Filtr</p>
                <input type="text" id="target" class="mb-2 form-control form-control-lg bg-secondary" />
                <p>Klient (ID, Imię, Nazwisko, Email):</p> 
              <select class="form-select bg-secondary text-light " name="obslugiwany_uzytkownik">
                {%for uzytkownik in uzytkownicy_lista%}
                <option data-obslugiwany="{{uzytkownik[0]}}{{uzytkownik[1]}}{{uzytkownik[2]}}{{uzytkownik[3]}}" class="obslugiwany-option" value="{{uzytkownik[0]}}"><span>#{{uzytkownik[0]}} {{uzytkownik[1]}} {{uzytkownik[2]}} {{uzytkownik[3]}}</span></option>
                {%endfor%}
              </select>

                <div class="row justify-content-around" style="margin-top:24px">
                  <input type="radio" class="inpcard inpcardN" id="normal" name="ticketType" value="NORMAL" checked="checked">
                  <div class="card card3 text-white bg-dark mb-3  col  col-xxl-4 col-12 " style=""><label for="normal">
                      <div class="card-header bg-success mt-2 text-dark fw-bold text-center"><label for="one">Normal</div>
                      <div class="card-body">
                          <h5 class="card-title">Długość karnetu: 1 miesiąc</h5>
                      </div>
                    </label>
                    <p class="mt-auto text-center text-success n fw-bold h4 mb-4">Cena: {{normal}} zł</p>
                  </div>
                
                  <input type="radio" class="inpcard inpcardP" id="pro" name="ticketType" value="PRO">
                  <div class="card card3 text-white bg-dark mb-3 col   col-xxl-4 col-12 " style=""><label for="pro">
                      <div class="card-header bg-warning mt-2 text-dark fw-bold text-center">Pro</div>
                      <div class="card-body">
                          <h5 class="card-title">Długość karnetu: 3 miesiące</h5>
                      </div>
                    </label>
                    <p class="mt-auto text-center text-warning fw-bold h4 mb-4">Cena: {{pro}} zł</p>
                  </div>
                
                  <input type="radio" class="inpcard inpcardM" id="max" name="ticketType" value="MAX">
                  <div class="card card3 text-white bg-dark mb-3 col   col-xxl-4 col-12 " style=""><label for="max">
                      <div class="card-header bg-danger mt-2 text-dark fw-bold text-center">Max</div>
                      <div class="card-body">
                          <h5 class="card-title">Długość karnetu: 6 miesięcy</h5>

                      </div>
                    </label>
                    <p class="mt-auto text-center text-danger fw-bold h4 mb-4">Cena: {{max}} zł</p>
                  </div>
                </div>


                <div class="text-center mx-auto bg-dark card mb-5 mt-5" style="max-width: 400px;opacity:0.95;">
                  <!-- <button type="submit" value="Zapłać">dasda</button> -->
                  <button type="submit" class="btn btn-primary p-3">Podaj datę aktywacji karnetu i dodaj karnet</button>
                  <input type="date" id="inputDate" name="inputDate" class="bg-dark border-0 text-light p-3" required>
                  <input type="string" id="inputEndDate" name="inputEndDate" style="display:none;">
                <div id="outputDate" class="text-light p-3">Wybierz datę i rodzaj karnetu.</div>
                </div>
                
                

            </form>
            </div>

           
            
        </div>
    </div>
</div>


<script>
  
  document.getElementById("inputDate").addEventListener("input", updateDate);
  var ticketTypeElements = document.getElementsByName("ticketType");
  
  for (var i = 0; i < ticketTypeElements.length; i++) {
      ticketTypeElements[i].addEventListener("change", updateDate);
  }
  
  function updateDate() {
      var selectedDate = document.getElementById("inputDate").value;
      var selectedTicketType;
  
      for (var i = 0; i < ticketTypeElements.length; i++) {
          if (ticketTypeElements[i].checked) {
              selectedTicketType = ticketTypeElements[i].value;
              break;
          }
      }
  
      var outputDateElement = document.getElementById("outputDate");
  
      if (selectedDate && selectedTicketType) {
          var newDate;
  
          if (selectedTicketType == "NORMAL") {
              newDate = new Date(selectedDate);
              newDate.setMonth(newDate.getMonth() + 1);
          } else if (selectedTicketType == "PRO") {
              newDate = new Date(selectedDate);
              newDate.setMonth(newDate.getMonth() + 3);
          } else if (selectedTicketType == "MAX") {
              newDate = new Date(selectedDate);
              newDate.setMonth(newDate.getMonth() + 6);
          }
  
          var formattedDate = newDate.toLocaleDateString();
          outputDateElement.textContent = "Data wygaśnięcia karnetu: " + formattedDate;
          document.getElementById("inputEndDate").setAttribute('value',newDate.toISOString().slice(0, 10));
      } else {
          outputDateElement.textContent = "Wybierz datę i rodzaj karnetu.";
      }
  }


  document.getElementById('target').addEventListener('input', function() {
      var inputText = this.value.toLowerCase();
      var options = document.getElementsByClassName('obslugiwany-option');

      for (var i = 0; i < options.length; i++) {
            var optionText = options[i].getAttribute('data-obslugiwany').toLowerCase();
            options[i].style.display = optionText.includes(inputText) ? 'block' : 'none';
        }

        for (var i = 0; i < options.length; i++) {
            if (options[i].style.display !== 'none') {
                options[i].selected = true;
                break;
            }
        }
  });

  </script>
{%endblock%}

app/templates/lista_uczestnikow_zajec.html
{%extends "base.html"%}
{%block content%}
  <div class="row justify-content-around" style="margin-top:12px">
    <div class="card cardp text-white bg-dark mb-3" style="">
        <div class="card-body">
            <h5 class="card-title text-primary">Lista uczestnikow zajęc</h5>
            <hr class="bg-light">
            <p class="card-text">
                Nazwa zajęć: {{ dane_o_zajeciach[0][0] }}</br>
                Data zajęć: {{ dane_o_zajeciach[0][3] }}</br>
                Godzina rozpoczęcia: {{ dane_o_zajeciach[0][1] }}</br>
                Czas trwania (w min): {{ dane_o_zajeciach[0][2] }}</br>
                Maksymalna liczba uczestników: {{ dane_o_zajeciach[0][4] }}</br>
                
            </p>
            
            <div class="table-responsive ">
                <table class="table table-striped table-dark ">
                    <thead>
                        <tr>
                            <th scope="col">ID uczestnika</th>
                            <th scope="col">Imię</th>
                            <th scope="col">Nazwisko</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for uczestnik in lista_uczestnikow %}
                            <tr>
                                <th >{{ uczestnik[0] }}</th>
                                <td>{{ uczestnik[1] }}</td>
                                <td>{{ uczestnik[2] }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

          
          
        </div>
    </div>
</div>
{%endblock%}

app/templates/logowanie copy.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>silownia</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="../static/styles.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-black px-4">
    <a class="navbar-brand" href="#">LetsBeFit</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Strona główna </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">O nas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Oferta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Zaloguj się</a>
        </li>
        
      </ul>
    </div>
  </nav>



  <form class="rejlog" action="logowanie_action" method="post">
    <p>Logowanie</p>
    <input type="text" name="login" placeholder="Login"/></br>
    <input type="password" name="haslo" placeholder="Hasło"/></br>
    <input type="submit" name="zaloguj_przycisk" value="Zaloguj"/>
    
    <p>Nie masz konta? <a href="/rejestracja">Zarejestruj się</a></p>
    <p>{{msg}}</p>
    </form>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>

</html>

app/templates/profil.html
{%extends "base.html"%}
{%block content%}
  <div class="row justify-content-around" style="margin-top:12px">
    <div class="card cardp text-white bg-dark mb-3" style="">
        <div class="card-body">
            <h5 class="card-title text-primary">Profil użytkownika</h5>
            <hr class="bg-light">
            <p class="card-text">
                Status karnetu: {% if status_karnetu=="aktywny" %}<b class="text-success">Aktywny</b>{% endif %}
                {% if status_karnetu=="nieaktywny" %}<b class="text-danger">Nieaktywny</b>{% endif %}</br>
                Imię: {{ imie }}</br>
                Nazwisko: {{ nazwisko }}</br>
                E-mail (login): {{ login }}</br>
                Nr telefonu: {{ nr_tel }}</br>
                Płeć: {{ plec }}</br>
                Data dołączenia: {{ data_dolaczenia }}</br>
            </p>
            <input type="hidden" name="imie" value="{{ imie }}">
            <input type="hidden" name="nazwisko" value="{{ nazwisko }}">
            <input type="hidden" name="typ_karnetu" value="{{ typ_karnetu }}">
            <input type="hidden" name="cena" value="{{ cena }}">
            <input type="hidden" name="data_rozpoczecia" value="{{ data_rozpoczecia }}">
            <input type="hidden" name="data_konca" value="{{ data_konca }}">
            <h5 class="card-title text-primary">Historia zakupionych karnetów</h5>
            
            <div class="table-responsive ">
                <table class="table table-striped table-dark ">
                    <thead>
                        <tr>
                            <th scope="col">ID karnetu</th>
                            <th scope="col">Typ karnetu</th>
                            <th scope="col">Wartość</th>
                            <th scope="col">Data zakupu</th>
                            <th scope="col">Data aktywacji</th>
                            <th scope="col">Data wygaśnięcia</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ticket in ticket_list %}
                            <tr>
                                <th scope="row">{{ ticket[0] }}{% if ticket[0] in karnety_ids %}<span class="text-success"> (aktywny)</span>{% endif %}</th>
                                <td>{{ ticket[1] }}</td>
                                <td>{{ ticket[2] }}</td>
                                <td>{{ ticket[3] }}</td>
                                <td>{{ ticket[4] }}</td>
                                <td>{{ ticket[5] }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="pagination justify-content-center">
              <ul class="pagination">
                  {% if pagination.has_prev %}
                      <li class="page-item">
                          <a class="page-link" href="{{ url_for('profile.profil', page=pagination.prev_num) }}" aria-label="Previous">
                              <span aria-hidden="true">&laquo;</span>
                          </a>
                      </li>
                  {% endif %}
                  
                  {% for page_num in pagination.pages %}
                      {% if page_num == pagination.page %}
                          <li class="page-item active"><span class="page-link">{{ page_num }}</span></li>
                      {% else %}
                          <li class="page-item"><a class="page-link" href="{{ url_for('profile.profil', page=page_num) }}">{{ page_num }}</a></li>
                      {% endif %}
                  {% endfor %}
                  
                  {% if pagination.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="{{ url_for('profile.profil', page=pagination.next_num) }}" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                          </a>
                      </li>
                  {% endif %}
              </ul>
          </div>
          
        </div>
    </div>
</div>
{%endblock%}

app/templates/reset_hasla.html
{%extends "base.html"%}
{%block content%}
<div class="row justify-content-around" style="margin-top:24px">
  <div class="card card3 text-white bg-dark mb-3  col  col-xxl-4 col-12 " style="">  
      <div class="card-body ">
        <h5 class="card-title text-primary">Resetowanie hasła</h5>
            <hr class="bg-light">
            <p class="text-success">{{msgSuccess}}</p>
        <form method="post" action="{{ url_for('auth.reset_hasla') }}">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <label for="email" class="mb-2" >Email:</label>
          <input type="email" name="email"  class="form-control form-control-lg bg-secondary" required></br>
          <div class="d-flex justify-content-center">
          <button type="submit" class="btn btn-primary p-3 mb-3 mx-auto">Wyślij link resetujący</button>
          </div>
        </form>
      </div>
  </div>
  </div>
{%endblock%}

app/templates/reset_hasla_potwierdzenie.html
{%extends "base.html"%}
{%block content%}

<div class="row justify-content-around" style="margin-top:24px">
  <div class="card card3 text-white bg-dark mb-3  col  col-xxl-4 col-12 " style="">  
      <div class="card-body ">
        <h5 class="card-title text-primary">Zmiana hasła na nowe</h5>
            <hr class="bg-light">
        <form method="post" action="{{ url_for('auth.reset_hasla_potwierdzenie', token=token) }}">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <!-- Pozostałe pola formularza -->
          {{msg}}
          <label for="nowe_haslo">Nowe hasło:</label>
          <input type="password" id="nowe_haslo" name="nowe_haslo" class="form-control form-control-lg bg-secondary" required>
          <label for="nowe_haslo2">Powtórz hasło:</label>
          <input type="password" id="nowe_haslo2" name="nowe_haslo2" class="form-control form-control-lg bg-secondary" required></br>
          <div class="d-flex justify-content-center">
          <input type="submit" class="btn btn-primary p-3 mb-3 mx-auto" value="Zresetuj hasło">
          </div>
        </form>
      </div>
  </div>
  </div>
{%endblock%}